#Chatbot for BRACU info
#import Libraries
import nltk
from nltk.chat.util import Chat,reflections


print("This is BRACU bot which provides information about CSE courses. You can ask 'Who are you?' to know about the bot or by course code to know about the course. For example: cse110 or CSE110 (Without space).If you are finished asking questions. Say Bye.")
pairs = [
    ['my name is (.*)' , ['hi %1', 'hey %1']],
    ['(hey|hello|hi|hey there| hola)',['hi there' , 'hello there' , 'haaaay']],
    ['Who are you?',["my name is BRACU bot. I provide information about Bracu CSE courses. Please ask me by course code."]],
    ['(CSE101|cse101)',['CSE 101: Introduction to Computer Science (3 credits)-> Introduction to the use of computer hardware and software as tools for solving problems. Automated input devices and output methods (including pre-printed stationary and turnaround documents) as part of the solution.']],
    ['(CSE110|cse110)',['CSE 110: Programming Language I (3 credits) This course would be an introduction to the foundations of computation and purpose of mechanized computation. Emphasis will be placed on techniques of problem analysis and the development of algorithms and programs.']],
    ['(CSE111|cse111)',['CSE 111: Programming Language-II (3 credits) This course would be an introduction to data structures, formal specification of syntax, elements of language theory and mathematical preliminaries. Other topics that would be covered are formal languages, structured programming concepts, survey of features of existing high level languages. Students would design and write application using an appropriate language.']],
    ['(CSE220|cse220)',['CSE 220: Data Structures (3 credits)-> Introduction to widely used and effective methods of data organisation, focussing on data structures, their algorithms and the performance of these algorithms. Concepts and examples, elementary data objects, elementary data structures, arrays, lists, stacks, queues, graphs, trees, compound structures, data abstraction and primitive operations on these structures. memory management; sorting and searching; hash techniques; Introduction to the fundamental algorithms and data structures: recursion, backtrack search, lists, stacks, queues, trees, operation on sets, priority queues, graph dictionary. ']],
    ['(CSE221|cse221)',['CSE 221: Algorithms (3 credits)-> The study of efficient algorithms and effective algorithm design techniques. Techniques for analysis of algorithms, Methods for the design of efficient algorithms :Divide and Conquer paradigm, Greedy method, Dynamic programming, Backtracking, Basic search and traversal techniques, Graph algorithms, Elementary parallel algorithms, Algebraic simplification and transformations, Lower bound theory, NP-hard and NP-complete problems.']],
    ['(CSE230|cse230)',['CSE 230: Discrete Mathematics (3 credits)-> Set theory, Elementary number theory, Graph theory, Paths and trees, Boolean Algebra, Binary Relations, Functions, Algebraic system, Generating functions, Induction, Reduction, Semigroup, Permutation groups, Discrete Probability, Mathematical logic, Prepositional calculus and Predicate calculus.']],
    ['(CSE250|cse250)',['Fundamental electrical concepts and measuring units. Direct current: voltage, current, resistance and power. Laws of electrical circuits and methods of network analysis; Introduction to magnetic circuits. Alternating current: instantaneous and r.m.s. current, voltage and power, average power for various combinations of R, L and C circuits, phasor representation of sinusoidal quantities. The course includes a compulsory 3 hour laboratory work alternate week.']],
    ['(CSE251|cse251)',['CSE 251 Electronic Devices and Circuits (3 credits)-> Introduction to semiconductors, p-type and n-type semiconductors; p-n junction diode characteristics; Diode applications: half and full wave rectifiers, clipping and clamping circuits, regulated power supply using zener diode.Bipolar Junction Transistor (BJT): principle of operation, I-V characteristics; Transistor circuit configurations (CE, CB, CC), BJT biasing, load lines; BJTs at low frequencies; Hybrid model, h parameters, simplified hybrid model; Small-signal analysis of single and multi-stage amplifiers, frequency response of BJT amplifier.']],
    ['(CSE260|cse260)',['CSE 260: Digital Logic Design (3 credits)-> An introduction to digital systems such as computer, communication and information systems. Topics covered include Boolean algebra, digital logic gates, combinational logic circuits, decoders, encoders, multiplexers. Asynchronous and synchronous counters. Registers, flip-flops, adders, Sequential circuit analysis and design. Simple computer architecture. The course includes a compulsory 3 hour laboratory work each week.']],
    ['(CSE310|cse310)',['CSE 310: Object Oriented Programming ( 3 credits)-> An introduction to object oriented programming using. Java is the language typically used to illustrate the concepts, but another suitable language may be substituted by the instructor. Topics covered include object instances, classes, inheritance, polymorphism and abstraction mechanism. Problem domain analysis and system design using object oriented approach. Object oriented database and object persistency. Software principles for object oriented approach. Advantages and problems with using object oriented approach to developing systems. The course includes a compulsory 3 hour laboratory work each week.']],
    ['(CSE320|cse320)',['CSE 320: Data Communications (3 credits)-> Introduction to purpose and methods of communication. Necessity for modulation and techniques. Technical aspects of data communications. Effects of noise and control. Basic concepts such as fundamental limits, encoding, modulation, multiplexing, error detection and control. Topics include: Data Transmission Protocols, different layers in data communication systems, LANs, WANs linked with telephony. This course will include a compulsory 3-hour laboratory work each week for those interested in obtaining the CCNA certification.']],
    ['(CSE321|cse321)',['CSE 321: Operating Systems ( 3 credits)-> Principles of operating systems: design objects; sequential process; concurrent processes, functional mutual exclusion, processor co-operation and deadlocks, management. Control and scheduling of large information processing systems. Dispatching processor access methods, job control languages memory addressing, paging and store multiplexing, and time sharing, batch processing. Scheduling algorithms, file systems, and security; semaphores and critical sections, device drivers, multiprocessing, sharing, design and implementation methodology, performance evaluation and case studies. The course includes a compulsory 3 hour laboratory work each week.(Pre req.: CSE 221)']],
    ['(CSE330|cse330)',['CSE 330: Numerical Methods ( 3 credits)-> Computer Arithmetic: floating point representation of numbers, arithmetic operations with normalized floating point numbers; Iterative methods: different iterative methods for finding the roots of an equation and their computer implementation; Solution of simultaneous Algebraic Equations, Gauss elimination; Interpolation, Least square approximation of functions, Taylor series representation, Chebyshev series; Numerical differentiation and integration and Numerical Solution of Differential Equations.( Pre req.: MAT 120)']],
    ['(CSE331|cse331)',['CSE 331: Automata and Computability (3 credits)-> An introduction to finite representation of infinite objects and basic mathematical models of computation. Finite automata and regular languages, pushdown automata and context free languages. Turing machines. Church\'s Thesis. Partial recursive functions. Undecidability. Reducibility and completeness. Halting problem. Time complexity and NP-completeness. Probabilistic computation. Interactive proof systems. (Pre req.:CSE221)']],
    ['(CSE340|cse340)',['CSE 340: Computer Architecture (3 credits)-> systematic study of the various elements in computer design, including circuit design, storage mechanisms, addressing schemes, and various approaches to parallelism and distributed logic. Information representation and transfer; instruction and data access methods; the control unit; hardware and microprogrammed; memory organisation. RISC and CSEC machines. (Pre req. CSE 260)']],
    ['(CSE341|cse341)',['CSE 341: Microprocessors (3 credits)-> Introduction to different types of microprocessors. Microprocessor architecture, instruction set, interfacing/O operation, interrupt structure, DMA. Microprocessor interface ICs. Advanced microprocessor concept of microprocessor based system design.The course includes a compulsory 3 hour laboratory work each week.( Pre req. CSE 260)']],
    ['(CSE342|cse342)',['CSE 342: Computer System Engineering (3 credits)-> Topics on the engineering of computer software and hardware systems: techniques for controlling complexity; networks and distributed systems; atomicity and coordination of parallel activities; recovery and reliability; privacy of information; impact of computer systems on society. Case studies of working systems and outside reading in the current literature provide comparisons and contrasts.']],
    ['(CSE350|cse350)',['Diode logic gates, transistor switches, transistor gates, MOS gates, Logic families: TTL, ECL, IIL and CMOS logic with operation details. Propagation delay, product and noise immunity. Open collector and High impedance gates. Electronic circuits for flip flops, counters and register, memory systems. PLA\'s (A/D, D/A converters with applications, S/H circuits) LED, LCD and optically coupled oscillators. Non-linear applications of OPAMPs. Analog switches. Linear wave shaping: diode wave shaping techniques, clipping and clamping circuits, comparator circuits, switching circuits. Pulse transformers, pulse transmission. Pulse generation:monostable, bistable and stable multivibrations, Timing circuits. Simple voltage sweeps, linear circuit sweeps. Schmitrigger, blocking oscillators and time base circuit. The course includes a compulsory 3 hour laboratory work each week.(Pre req. CSE 251, CSE 260)']],
    ['(CSE360|cse360)',['CSE 360: Computer Interfacing (3 credits)-> Interface components and their characteristics, micro processor I/O. Disk, Drums and Printers. Optical displays and sensors. High power interface devices, transducers, stepper motors and peripheral devices. The course includes a compulsory 3 hour laboratory work alternate week.(Pre req. CSE 341)']],
    ['(CSE370|cse370)',['CSE 370: Database Systems (3 credits)-> Introduction to concepts and methods for storing and manipulating data in stored form. File retrieval and organisation. Database models and designing of database systems. The principles of database management systems. Relational database management systems. Query formulation and language. Database administration. Methods used for the storage, selection and presentation of Data. Database integrity and security. Students will work with database languages and popular application packages. Common database management systems. Structure of SQL and principals behind the design of SQL. Students must complete four SQL assignments in the lab. The course includes a compulsory 3 hour laboratory work each week.(Pre req. CSE 221)']],
    ['(CSE371|cse371)',['CSE 371: Management Information Systems (3 Credits)-> Computer & information processing; Strategic information systems; Software, hardware and telecommunications; System building methods; Transaction processing system; Office automation; DeCSEion support systems; Executive support systems; Artificial intelligence; Computer security & disaster planning; Ethical & social issues in information systems.']],
    ['(CSE390|cse390)',['CSE 390: Technical Communication (3 Credits)-> he fundamentals of technical communication using oral, written and visual means are presented as practised in industry and academia. Clarity of thought, organisational skills and systematic approaches are emphasised. Students engage in exercises that focus on technical writing, public speaking, graphic design and giving presentations. They apply their skills across a broad range of activities, including critique of presentations and writing of proposals, reports, memoranda, user manuals, instructional modules, and technical specifications. Techniques presented are intended to create an appreciation for format and content and to better prepare students for project documentation and formal presentations.(Prereq.: Permission of instructor)']],
    ['(CSE391|cse391)',['CSE 391: Programming for the Internet (3 Credits)-> A survey of current Internet technologies and state-of-the-art web programming methods. Using client/server structures, topics studied will be drawn from JavaScript, JSP, ASP, Cold Fusion, Flash, Document Object Model, HTML, Cascading Style Sheets, XML, CGI, TCP/IP and the .NET platform. Programming tools may include PERL, various UNIX shell scripts, Windows batch files, Java and other languages as needed.(Prereq.: CSE 220)']],
    ['(CSE392|cse392)',['CSE 392: Signals and Systems (3 Credits)-> The course deals with the topics of Fourier series, Fourier transforms, Laplace transform, time and frequency response, ideal low-pass filters, band-pass channels, analogue communications, amplitude modulation, angle modulation, frequency-division multiplexing, digital communications, pulse-code modulation, time-division multiplexing, random processes, stationarity, autocorrelation functions, spectral density, Gaussian processes, noise in analogue and digital modulation schemes.(Prereq.: MAT 215)']],
    ['(CSE410|cse410)',['CSE 410: Advanced Programming In UNIX ( 3 Credits)-> Exploration of the Unix operating system, including its tools and utilities for program development, such as makefile, piping and redirection, shell scripts, regular expressions, and symbolic debuggers. In addition, this course explores advanced features of the C programming language, including various file processing, command-line and variable arguments, exception handling, and generic interfacing. Multiprocessing and Multithreading programming in Unix/Linux C. Thread synchronization. Network programming and TCP/IP socket programming. The course includes a compulsory 3 hour laboratory work each week.(Pre req CSE 321)']],
    ['(CSE419|cse419)',['CSE 419: Programming Languages ( 3 credits)-> An introduction to the principles of functional, imperative, and logic programming languages. Topics covered include meta-circular interpreters, semantics (operational and denotational), type systems (polymorphism, inference, and abstract types), object-oriented programming, modules, and multiprocessing; case studies of contemporary programming languages. Programming experience and background in language implementation required.(Pre req.: CSE 111, and CSE 331 or permission of the instructor)']],
    ['(CSE420|cse420)',['CSE 420: Compiler Design ( 3 credits)-> heory and Practice; An introduction to compiler and interpreter design, with emphasis on practical solutions using compiler writing tools such as Yacc in UNIX, and the C programming language, Topics covered include: lexical scanners, context free languages and pushdown automata, recursive descent parsing, bottom up parsing, attributed grammars, symbol table design, run time memory allocation, machine language, code generation and optimisation. The course includes a compulsory 3 hour laboratory work alternate week.(Pre req.: CSE 221, and CSE 331 or permission of the instructor)']],
    ['(CSE421|cse421)',['CSE 421: Computer Networks (3 credits)-> An introduction to the basics of transport connections and sessions. The protocol hierarchy, design issues in transport and session layer protocol, end-to-end protocols, message handling protocols, terminal and file transfer protocols, Internet TCP/IP protocols. End to end data networks, congestion control networks, wireless networks, mobile computing, high speed networks. Concurrent programming, data link layer, framing and error control, media access control. Models of distributed computation, management and resource control of networks and distributed operating systems, distributed file systems, caching scheduling, process migration. Fault tolerance, network security and privacy, algorithm for deadlock detection. Synchronization and concurrency control in distributed systems. The course includes a compulsory 3-hour laboratory work each week if the student wishes to obtain CCNA certification. Otherwise the course includes a compulsory 3-hour laboratory work alternate week.Prerequisite: CSE 320 for CCNA certification.']],
    ['(CSE422|cse422)',['CSE 422: Artificial Intelligence (3 credits)-> Survey of concepts in artificial intelligence. Knowledge representation, search and Control techniques. AI machines and features of LISP and PROLOG languages. Problem Representation; search, constraint propagation, rule chaining, frame inheritance, inference and learning in intelligent systems; systems for general problems solving, game playing, expert consultation, concept formation and natural languages processing; recognition, understanding and translation. Use of heuristic vs. algorithmic programming; cognitive simulations - vs. machine intelligence; study of some expert systems such as robotics and understanding. Solving problems in Al languages. The course includes a compulsory 3 hour laboratory work each week.(Pre req. CSE 221)']],
    ['(CSE423|cse423)',['CSE 423: Computer Graphics (3 credits)-> Introduction to Graphical data processing. Fundamentals of interactive graphics Architecture of display devices and connectivity to a computer. Implementation of graphics concepts of two dimensional and three dimensional viewing, clipping and transformations. Hidden line algorithms. Raster graphics concepts: Architecture,algorithms and other image synthesis methods. Design of interactive graphic conversations. The course includes a compulsory 3 hour laboratory work alternate week.(Pre req. MAT 215)']],
    ['(CSE424|cse424)',['CSE 424: Pattern Recognition (3 credits)-> Introduction to pattern recognition: features, classifications, learning. Statistical methods, structural methods and hybrid method. Applications to speech recognition, remote sensing and biomedical area. Learning algorithms, Syntactic approach: Introduction to pattern grammars and languages. Parsing techniques. Pattern recognition in computer aided design. The course includes a compulsory 3 hour laboratory work alternate week.( Pre req. MAT 215)']],
    ['(CSE425|cse425)',['CSE 425: Neural Networks (3 credits)-> An extensive course on neural network architectures and learning algorithms with theory and applications. Temporal and optimal linear associative memories, fuzzy control. Cohen-Grossberg theorem. Unsupervised learning. Higher-order competitive, differential Hebbian learning networks. Supervised learning. Adaptive estimation and stochastic approximation. Adaptive vector quantization, mean-square approach. Kohonen self-organizing maps. Grossberg theory. Simulated annealing. Boltzman and Cauchy learning. Adaptive resonance. Gabor functions and networks.']],
    ['(CSE426|cse426)',['CSE 426: Basic Graphs Theory (3 credits)-> Graphs and simple graphs, diagraphs, subgraphs, vertex-degrees, walks,, paths and cycles; trees, spanning trees in graphs, distance in graphs; Complementary graphs, cut-vertices, bridges and blocks, k-connected graphs; Euler tours, Hamiltonian cycles, Chinese Postman Problem, Traveling Salesman Problem; Chromatic number, Chromatic polynomials, chromatic index, Vizing\'s theorem, planar graphs, perfect graphs.']],
    ['(CSE427|cse427)',['CSE 427: Machine Learning (3 credits)-> Introduction to machine learning; Supervised and reinforcement learning; Unsupervised learning algorithms; Attribute based and relational supervised learning algorithms; Neural network based learning algorithms; Genetic algorithm and genetic programming; Reinforcement learning algorithms; Computational learning theory.']],
    ['(CSE428|cse428)',['CSE 428: Image Processing (3 credits)-> Digital image fundamentals, perception, representation; image transforms; First Fourier Transform (FFT), Discrete Cosine Transform (DCT), Karhumen and Loeve Transform (KLT), Wavelet transform and sub-band decomposition; image enhancement and restoration techniques, image compression techniques, image compression standards: JPEG, MPEG, H.261, and H.263.']],
    ['(CSE429|cse429)',['CSE 429: Basic Multimedia Theory (3 credits)-> Multimedia System- Introduction; Coding of compression standards; Architecture issues in multimedia; Operating System issues in multimedia- real-time OS issues, synchronization, interrupt handling; Database issues in multimedia- indexing and storing multimedia data, disk placement, disk scheduling, searching for a multimedia document; Networking issues in multimedia- Quality-of service guarantees, resource reservation, traffic specification, happing and monitoring, admission control; Security issues in multimedia- digital water-marking, partial encryption schemes for video streams; Multimedia application- audio and video conferencing, video on demand, voice over IP. Concepts covered in lecture applied in computer laboratory assignments.']],
    ['(CSE430|cse430)',['Introduction to Digital Signal Processing, Filtering, Frequency response, Sampling theory, Z-transform, Discrete Fourier Transform (DFT), Fast Fourier Transform (FFT), Windowing, Correlation & Convolution, Application of Digital Signal Processing. Introduction to Digital Filters, Finite Impulse Response (FIR), Infinite Impulse Response (IIR), Different techniques of FIR and IIR filter design. MATLAB application to DSP; the course includes a compulsory 3-hour laboratory work each week. (Pre req. CSE 111 and MAT120)']],
    ['(CSE431|cse431)',['CSE 431: Natural Language Processing (3 credits)-> ntroduction to the field of natural language processing (NLP)- the creation of computer programs that can understand, generate, and learn natural language. The topics include the three major subfields of NLP: syntax (the structure of an utterance), semantics (the truth-functional meaning of an untterance), and pragmatics/discourse (the context-dependent meaning of an utterance). The course will introduce both knowledge-based and statistical methods for NLP, and will illustrate the use of such methods in a variety of of text- and speech-based application areas.(Pre req. CSE 111, and CSE 422 or consent of the instructor)']],
    ['(CSE432|cse432)',['CSE 432: Speech Recognition and Synthesis (3 credits)-> Introduction to automatic speech recognition, speech understanding and speech synthesis/text-to-speech from the computer science and linguistics perspective. Focus on understanding of key algorithms including noisy channel model, Hidden Markov Models (HMMs), A* and Viterbi decoding, N-gram language modeling, unit selection synthesis, and roles of linguistic knowledge (especially phonetics, intonation, pronunciation variation, disfluencies).(Pre req. CSE 111)']],
    ['(CSE460|cse460)',['CSE 460: VLSI Design (3 credits)-> Design and analysis techniques fro VLSI circuits. Design reliable VLSI circuits, noise considerations, design and operation of large fan out and fan in circuits, clocking methodologies, techniques for data path and data control design. Simulation techniques. Parallel processing, spatial purpose architectures in VLSI. VLSI layouts partitioning and placement routing and wiring in VLSI. Reliability aspects of VLSI design. The course includes a compulsory 3 hour laboratory work alternate week.(Pre req. CSE 350)']],
    ['(CSE461|cse461)',['CSE 461: Digital System Design (3 credits)-> Design using MSI and LSI components. Design of memory subsystem using SRAM and DRAM. Design of various components of a computer: ALU, memory and control unit: hardwired and micro programmed. Microprocessor based designs. Computer bus standards. Design using special purpose controllers, floppy disk controller. Digital control system. Computes in telecommunication and control. The course includes a compulsory 3 hour laboratory work each week.( Pre req. CSE 260)']],
    ['(CSE462|cse462)',['Introduction to Fault Tolerant Systems and Architectures. Fault detection and location in combinational and sequential circuits; Fault test generation for combinational and sequential circuits; Digital simulation as a diagnostic tool. Automatic test pattern generator, memory test pattern and reliability. Performance monitoring self checking circuits, Burst error correction and Triple modular redundancy; Maintenanceprocessors.']],
    ['(CSE470|cse470)',['CSE 470: Software Engineering (3 credits)-> Concepts of software engineering: requirements definition, modular, structure design, data specifications, functional specifications, verification, documentation, software maintenance, Software support tools. Software project organization, quality assurance, management and communication skills.']],
    ['(CSE471|cse471)',['CSE 471: System analysis and design ( 3 credits)-> Introduces students to tools and techniques in systems analysis and design such as data flow diagram and E-R diagrams. Projects by students where they analyse and design a system using these tools. The course includes a compulsory 3 hour laboratory work each week.']],
    ['(CSE472|cse472)',['CSE 472: Human Computer Interface (3 credits)-> An introduction to the concepts for human and computer interface. The importance of computer interface, interface quality and methods of evaluation. The relationship of interface quality to interactions with the computer. Interface design, dimensions of interface variability, dialogue tools and techniques, user centered design and task analysis. User interface implementation, I/O devices and user interface for groupware, multimedia systems and visualization. Student will have to submit four assignments on multimedia work in the lab.(Pre req. CSE 221)']],
    ['(CSE473|cse473)',['CSE 473: Decision Support Systems (3 Credits)-> his course aims in teaching the integration of business and technical consideration in the design, implementation and management of information systems. Topics include: Is planning and development, business, management, executive, and strategic information systems, including case studies of selected large disaster planning and recovery. The course also includes practical examples of information systems industry.']],
    ['(CSE474|cse474)',['CSE 474: Simulation and Modeling (3 credits)-> Simulation methods, model building, random number generator, statistical analysis of results, validation and verification techniques. Digital simulation of continuous system. Simulation and analytical methods for analysis of computer system and practical problems in business and practice. Introduction to the simulation packages. The course includes a compulsory 3 hour laboratory work alternate week.(Pre req. MAT 215)']],
    ['(CSE490|cse490)',['CSE 490: WAN Routing and Technologies (Special Topics) (3 credits)-> The course focuses on advanced IP addressing techniques (Variable Length Subnet Masking [VLSM]), intermediate routing protocols (RIP v2, single-area OSPF, EIGRP), command-line interface configuration of switches, Ethernet switching, Virtual LANs (VLANs), Spanning Tree Protocol (STP), and VLAN Trunking Protocol (VTP). The course will also focus on advanced IP addressing techniques (Network Address Translation [NAT], Port Address Translation [PAT], and DHCP), WAN technology and terminology, PPP, ISDN, DDR, Frame Relay, network management, and introduction to optical networking. The course includes a compulsory 3-hour laboratory work each week if the student wishes to obtain CCNA certification.Prereq.: CSE 320 and CSE 421']],
    ['(CSE491|cse491)',['CSE 491: Independent Study (3 credits)-> For students interested in any of the following ways of studying Computer Science & Engineering: independently exploring an advanced topic under a faculty instructor; conducting significant research under a faculty supervisor; or doing an internship in industry under the supervision of industry and faculty advisors. In each case, the student must first identify a faculty member within the CSE department to oversee his/her work, and then write a proposal to the department chair outlining the means and objectives of the project. The proposal must be approved by the intended faculty supervisor and department chair prior to commencement of the term. At the end of the term, the student must submit a detailed report and/or give a presentation of the results, before the final course grade may be awarded.(Prereq.: Permission of instructor)']],
    ['(Bye|bye)',['See you again','Bye','See you later']],
]

chat = Chat(pairs, reflections)
chat.converse()

print(reflections)
